function hovering_controller_impl(varargin)
% HOVERING_CONTROLLER_IMPL  Geometric hover control over UDP (single UAV).
%
% Reads simulator state packets, computes the shared geometric hover control
% (uavsim.Control), and sends rotor commands back. Numerically identical to
% the Python reference controller (wheeled_uav/controllers/hover.py).
%
% Name/value options beyond the shared uavsim.RunOptions set:
%   'target_position'  [x; y; z] hover target in world coordinates
%                      (default [0; 0; 1.5])
close all; clc;

runtime_options = uavsim.RunOptions.parse(varargin, { ...
    'target_position', [0.0; 0.0; 1.5], @(value) isnumeric(value) && numel(value) == 3 ...
});
project_directory = fileparts(fileparts(fileparts(mfilename('fullpath'))));
controller_session = uavsim.Session.start( ...
    project_directory, ...
    runtime_options, ...
    'simulator_root', uavsim.Util.resolve_path_option(runtime_options.simulator_root, project_directory), ...
    'params_path', uavsim.Util.resolve_path_option(runtime_options.params_path, fullfile(project_directory, 'vehicle_params.json')), ...
    'generated_xml_directory', uavsim.Util.resolve_path_option(runtime_options.generated_xml_directory, fullfile(project_directory, 'build', 'generated_xml')) ...
);
vehicle_params = controller_session.vehicle_params;
instance_options = controller_session.instance_options;
controller_socket = controller_session.controller_socket;
socket_cleanup_handler = onCleanup(@() uavsim.Session.cleanup_socket(controller_socket));
simulator_cleanup_handler = onCleanup(@() uavsim.Launch.cleanup_simulator_process(controller_session.simulator_process_id, controller_session.simulator_options));

target_position = reshape(double(runtime_options.target_position), [], 1);
controller_config = vehicle_params.controller;
[allocation_matrix, mixer] = uavsim.Params.build_allocation_and_mixer(vehicle_params);
command_options = uavsim.Protocol.build_command_options(vehicle_params.command_mode, vehicle_params.thrust_coefficient, 'fidelity_mode', vehicle_params.fidelity.mode);
logging_options = uavsim.RunOptions.build_logging_options('hover', instance_options);
runtime_metrics = uavsim.Metrics.initialize();

logger_config = build_logger_config(vehicle_params, controller_config, target_position, allocation_matrix, mixer, command_options, instance_options);
logger = simulation_logger(project_directory, logger_config, logging_options);
% Initialized lazily from the first sample's absolute sim time: attaching to
% a simulator already at t >> interval must not trigger a save storm.
next_log_save_time = NaN;
cleanup_handler = onCleanup(@() uavsim.Session.finalize_controller_run(logger));

status_display_interval = 2.0;
next_status_time = 0.0;
start_time = NaN;
idle_deadline = tic;
udp_sample_tracker = [];

fprintf('Hover controller started (%s, recv=%d, send=%d). Press Ctrl+C to stop.\n', ...
    instance_options.label, ...
    instance_options.controller_local_port, ...
    instance_options.simulator_receive_port ...
);
uavsim.Session.display_logging_behavior(logger);

try
    while true
        state = uavsim.Protocol.read_latest_state(controller_socket);
        if isempty(state)
            if toc(idle_deadline) >= runtime_options.state_timeout_seconds
                runtime_metrics = uavsim.Metrics.note_timeout(runtime_metrics); %#ok<NASGU>
                error('uavsim:stateTimeout', 'No simulator state received within %.1f s.', runtime_options.state_timeout_seconds);
            end
            pause(0.001);
            continue;
        end

        idle_deadline = tic;
        uavsim.Protocol.assert_single_uav_state(state, 'hovering_controller');

        % One control evaluation per new simulator sample (docs/TIMING.md).
        [is_new_sample, udp_sample_tracker] = uavsim.Protocol.udp_state_is_new(state, udp_sample_tracker);
        if ~is_new_sample
            pause(0.0002);
            continue;
        end

        if isnan(start_time)
            start_time = double(state.time);
        end

        elapsed_simulation_time = double(state.time) - start_time;
        if isfinite(runtime_options.duration_seconds) && elapsed_simulation_time >= runtime_options.duration_seconds
            fprintf('Hover run complete at t=%.2f s\n', elapsed_simulation_time);
            break;
        end

        compute_timer = tic;
        rotor_thrusts = uavsim.Control.compute_hover_control( ...
            state, ...
            target_position, ...
            controller_config.desired_heading, ...
            vehicle_params.mass, ...
            vehicle_params.gravity, ...
            controller_config.position_gain, ...
            controller_config.velocity_gain, ...
            controller_config.attitude_gain, ...
            controller_config.angular_velocity_gain, ...
            mixer, ...
            vehicle_params.max_rotor_thrust, ...
            controller_config.position_error_limit_m, ...
            controller_config.max_tilt_deg ...
        );
        runtime_metrics = uavsim.Metrics.update(runtime_metrics, state, toc(compute_timer) * 1.0e3);

        control_command = uavsim.Protocol.build_control_command( ...
            rotor_thrusts, ...
            command_options, ...
            'sequence', runtime_metrics.command_sequence, ...
            'source_state_sequence', runtime_metrics.last_source_state_sequence, ...
            'wall_time_send_ns', uavsim.Util.wall_time_now_ns(), ...
            'controller_compute_ms', runtime_metrics.last_controller_compute_ms, ...
            'state_age_ms', runtime_metrics.last_state_age_ms, ...
            'state_sequence_gap', runtime_metrics.last_state_sequence_gap ...
        );
        uavsim.Protocol.send_control_command(controller_socket, control_command, controller_session.target_ip, controller_session.target_port);

        logger.append(state, control_command, target_position);

        if isnan(next_log_save_time)
            next_log_save_time = double(state.time) + logging_options.periodic_interval_seconds;
        end
        if uavsim.RunOptions.should_save_log_periodically(logging_options, state.time, next_log_save_time)
            logger.save_snapshot(double(state.time), 'periodic');
            if logging_options.print_save_events
                fprintf('Simulation log checkpoint saved at t=%.2f s -> %s\n', double(state.time), logger.get_file_path());
            end
            next_log_save_time = double(state.time) + logging_options.periodic_interval_seconds;
        end

        if state.time >= next_status_time
            display_status(state, target_position, control_command, command_options, instance_options.label);
            next_status_time = state.time + status_display_interval;
        end
    end
catch execution_error
    if strcmp(execution_error.identifier, 'uavsim:stateTimeout')
        fprintf('\nController stopped: %s\n', execution_error.message);
        return;
    end
    rethrow(execution_error);
end
end


function display_status(state, target_position, control_command, command_options, instance_label)
position = reshape(double(state.position), [], 1);
position_error = target_position - position;
angular_velocity = reshape(double(state.angular_velocity_body), [], 1);
command_values = uavsim.Protocol.displayed_command_values(control_command, command_options);
realtime_factor = uavsim.Protocol.get_realtime_factor(state);
fprintf( ...
    '[%s t=%.2f s, rtf=%.2f] pos=[%.3f %.3f %.3f] m, err=[%.3f %.3f %.3f] m, omega=[%.3f %.3f %.3f] rad/s, cmd=%s [%.3f %.3f %.3f %.3f] %s\n', ...
    instance_label, ...
    state.time, ...
    realtime_factor, ...
    position(1), position(2), position(3), ...
    position_error(1), position_error(2), position_error(3), ...
    angular_velocity(1), angular_velocity(2), angular_velocity(3), ...
    command_options.input_mode, ...
    command_values(1), command_values(2), command_values(3), command_values(4), ...
    uavsim.Protocol.command_unit_label(command_options.input_mode) ...
);
end


function config = build_logger_config(vehicle_params, controller_config, target_position, allocation_matrix, mixer, command_options, instance_options)
config = struct( ...
    'controller', 'hovering_controller', ...
    'mass', vehicle_params.mass, ...
    'gravity', vehicle_params.gravity, ...
    'arm_x', vehicle_params.arm_x, ...
    'arm_y', vehicle_params.arm_y, ...
    'yaw_moment_ratio', vehicle_params.yaw_moment_ratio, ...
    'max_rotor_thrust', vehicle_params.max_rotor_thrust, ...
    'thrust_coefficient', vehicle_params.thrust_coefficient, ...
    'rotor_geometry', vehicle_params.rotors, ...
    'position_gain', controller_config.position_gain, ...
    'velocity_gain', controller_config.velocity_gain, ...
    'attitude_gain', controller_config.attitude_gain, ...
    'angular_velocity_gain', controller_config.angular_velocity_gain, ...
    'position_error_limit_m', controller_config.position_error_limit_m, ...
    'max_tilt_deg', controller_config.max_tilt_deg, ...
    'desired_heading', controller_config.desired_heading, ...
    'target_position', target_position, ...
    'allocation_matrix', allocation_matrix, ...
    'mixer', mixer, ...
    'command_mode', command_options.input_mode, ...
    'fidelity_mode', vehicle_params.fidelity.mode, ...
    'network_fidelity', vehicle_params.fidelity.network, ...
    'instance_id', instance_options.instance_id, ...
    'instance_label', instance_options.label ...
);
end
